apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: main-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: config-bundle-secret
  components:
    - kind: objectstorage
      managed: false
