apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/my-bridge
  name: network-host-device-enp3s0
  namespace: vmtest
spec:
  config: >-
    {
      "name":"network-host-device-enp3s0",
      "type":"host-device",
      "cniVersion":"0.3.1",
      "macspoofchk":true,
      "ipam":{}
    }